
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    open-pull-requests-limit: 15
    schedule:
      interval: "weekly"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
