---
name: CI

on:
  push:
    branches: ["main"]
    paths:
      - "*.json"
  pull_request:
    branches: ["main"]
    paths:
      - "*.json"
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  flatpak:
    name: Flatpak
    runs-on: ${{ matrix.configuration.runs-on }}

    strategy:
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
      matrix:
        configuration:
          - arch: x86_64
            runs-on: ubuntu-latest
          - arch: aarch64
            runs-on: ubuntu-24.04-arm

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:8-${{ matrix.configuration.arch }}
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust SDK extension
        run: |
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y --arch=${{ matrix.configuration.arch }} org.freedesktop.Sdk.Extension.rust-stable//25.08

      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: com.github.davidmhewitt.torrential.json
          run-tests: ${{ matrix.configuration.arch == 'x86_64' }}
          repository-name: appcenter
          repository-url: https://flatpak.elementaryos.org/repo.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}"
          branch: daily
          arch: ${{ matrix.configuration.arch }}
