name: Update Flatpak Modules

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches: [ "rewrite" ]
    paths:
      - 'Cargo.lock'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: torrential

    - uses: actions/checkout@v3
      with:
        repository: flatpak/flatpak-builder-tools
        path: tools

    - name: Update modules
      run: |
        sudo apt-get install -y python3-toml python3-aiohttp
        python3 tools/cargo/flatpak-cargo-generator.py -o torrential/cargo-sources.json torrential/Cargo.lock

    - uses: peter-evans/create-pull-request@v4
      with:
        path: torrential
        commit-message: Automated update of cargo-sources.json
        title: Automated update of cargo-sources.json
